spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://47.105.221.99:3306/cotenant?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: youyu
      password: j39FK2s
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: fansbox-hikari
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 47.105.221.99
