spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://47.105.221.99:3306/cotenant?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: youyu
      password: j39FK2s
      driver-class-name: com.mysql.cj.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: fansbox-hikari
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 47.105.221.99
  thymeleaf:
    prefix: classpath:/templates/
qiniu:
  access-key: JfvKpmCZqfM2nzKXP49Bhe3LUIo1nX_9UneS3EL0
  secret-key: JFBrCeLMSeMvkzQUQ-Jr5RbZoX7PzSEiFvyMxuOG
  bucket: xiaoyouhezu_dev
  bucket-url: qiniutest001.fensibox.com
goeasy:
  cdn-host: cdn.goeasy.io
  rest-host: rest-hangzhou.goeasy.io
  app-key: BC-0a302f5f67764730b09e4be87bf06f0f
